language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t praveenchandran81/docker-react-travis-aws -f Dockerfile.dev .

script:
  - docker run praveenchandran81/docker-react-travis-aws npm run test -- --coverage

